- name: Create Tomcat directory
  file: "path=/home/ec2-user/Tomcat state=directory"

- name: Check if required version of tomcat already exists in the server
  stat: "path=/home/ec2-user/Tomcat/apache-tomcat-{{ tomcat_version }}"
  register: Version_exists

- name: Download Tomcat binary from Artifactory
  get_url:
    url: "http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/home/ec2-user/apache-tomcat-{{ tomcat_version }}.tar.gz"
    validate_certs: false
  when: Version_exists.stat.exists == False

- name: Untar Tomcat
  unarchive:
    src: "/home/ec2-user/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/home/ec2-user/Tomcat"
    remote_src: True
  when: Version_exists.stat.exists == False

- name: Removing the unwanted files
  file: "path=/home/ec2-user/Tomcat/apache-tomcat-{{ tomcat_version }}/{{ item }} state=absent"
  with_items:
      - LICENSE
      - NOTICE
      - RELEASE-NOTES
      - RUNNING.txt
  when: Version_exists.stat.exists == False

- name: Make bin dir executable
  file:
    path: "/home/ec2-user/Tomcat/apache-tomcat-{{ tomcat_version }}/bin"
    state: directory
    mode: 0755
    recurse: true

- name: starting Tomcat
  shell: "nohup /home/ec2-user/Tomcat/apache-tomcat-{{ tomcat_version }}/bin/startup.sh"
